export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export NIXPKGS_ALLOW_UNFREE=1
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="/run/user/1000"
export BIN="$HOME/bin"
export THIRD_PARTY_BIN="$HOME/.local/bin"
export APPIMAGES="$HOME/.appimages"
export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="st"
export VISUAL="$EDITOR"
export PAGER="less"
export LESSHISTFILE="-"
# export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export VIS_PATH="$XDG_CONFIG_HOME/vis/"
#export HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"

export RUBY="/home/vcc/.local/share/gem/ruby/3.0.0/bin"
export RVM="/home/vcc/.rvm/bin"
export ROSWELL="/home/vcc/.roswell/bin"
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export PATH="$PATH:$APPIMAGES:$BIN:$THIRD_PARTY_BIN:$ROSWELL:$RUBY:$RVM:/bin/"
